### ISSUE TITLE
[QUESTION] How can use multiple CPU to speed up optimization?

### ISSUE THREAD

**Issue by Penguinflash** [xsznix/keygen#4]
Hi. I want to speed up optimization, my PCs are insanely low end and each has only 2 cores.

What do I need to use multiple computers similar to the distcc, icecream compilers? 

Thanks!

**Comment by xsznix** [comment]
When I was actively working on this, I just opened up multiple instances of keygen in separate terminals until I had one instance for every CPU core. I don't have any experience with distributed computing, so how to scale up is completely up to you.
