### ISSUE TITLE
Carpalx - link in README.md is outdated

### ISSUE THREAD

**Issue by Glitchy-Tozier** [xsznix/keygen#5]
The link http://mkweb.bcgsc.ca/carpalx/?simulated_annealing in the README.md doesn't go anywhere. Actually, the whole Website (https://mkweb.bcgsc.ca/) seems to be gone.

**Comment by xsznix** [comment]
Seems to be back up.

**Comment by Glitchy-Tozier** [comment]
This is what I get shown:
![image](https://user-images.githubusercontent.com/59611881/194144550-e68e929e-4dd5-404d-9f0f-85643ddde381.png)

**Comment by xsznix** [comment]
Strange, it was up a few weeks ago: https://web.archive.org/web/20220923074233/http://mkweb.bcgsc.ca/

Well, when it's up, it's the source of truth about Carpalx.
